<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<RootNamespace>ITB_SCREEN_RECORDER.AgentWorker</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.Text.Json" Version="8.0.5" />
	</ItemGroup>

	<PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
		<DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>
	</PropertyGroup>

	<ItemGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
		<PackageReference Include="NAudio.Core" Version="2.3.0" />
		<PackageReference Include="NAudio.Wasapi" Version="2.3.0" />
		<PackageReference Include="System.Drawing.Common" Version="8.0.10" />
		<PackageReference Include="Vortice.Direct3D11" Version="3.6.2" />
		<PackageReference Include="Vortice.DXGI" Version="3.6.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ITB-SCREEN-RECORDER.Core\ITB-SCREEN-RECORDER.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>