<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ITB_SCREEN_RECORDER.Server</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="ClientApp\public\css\tailwind.min.css" />
    <Content Include="ClientApp\public\css\video-js.min.css" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ITB-SCREEN-RECORDER.Core\ITB-SCREEN-RECORDER.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="MediaMTX\" />
    <Folder Include="wwwroot\css\" />
  </ItemGroup>
  
  <ItemGroup>
    <None Update="MediaMTX\mediamtx.exe">
	  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="MediaMTX\mediamtx.yml">
	  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  
  <ItemGroup>
    <Content Update="wwwroot\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <Target Name="CompileFrontend" BeforeTargets="Build" Condition="Exists('ClientApp\package.json')">
	<Message Importance="high" Text="[ITB SCREEN RECORDER BUILD] Launching static Vite build from ClientApp..." />
	<Exec Command="npm run build -s &amp; exit 0" WorkingDirectory="ClientApp" />
  </Target>
</Project>
